name: Create release
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'skip-release')
    uses: libops/.github/.github/workflows/bump-release.yaml@8dfaf9c854df71d9bbffde48c5676ff07c543c51
    with:
      workflow_file: publish-rootfs.yaml
    permissions:
      contents: write
      actions: write
    secrets: inherit
